### ISSUE TITLE
Unreliable readings from the ECG

### ISSUE THREAD

**Issue by DRMacIver** [Protocentral/protocentral-healthypi-v3#2]
Hi,

I'm just experimenting with my new HealthyPi, but unfortunately I don't seem to be able to get at all reliable results for heart rate from the ECG. It frequently drops to zero for an extended period of time (in which I'm pretty sure my heart is not stopping), and often significantly under reports a lot of the rest of the time when compared to another presumed-good heart rate monitor I have (a v3.5 Contec CMS50F Pulse Oximeter).

This *could* be a sensor placement issue, but I don't think so - even if I stay very still the heart rate oscillates between extended periods of zero and apparently normal reading, and I've tried several sensor placements and it didn't seem to improve matters much.

Any idea what might be going on? Is there more information I can provide to help debugging?

**Comment by protocentralashwin** [comment]
@DRMacIver Thank you. 

In the original GUI which we had made, there we were a few bugs which were not fixed. A value of zero indicates Lead-off (contact) conditions. This is supposed to come as a message. 

We are also tweaking the ECG algorithm a bit more to remove motion artifacts. We will have a new release of the firmware and the GUI by tomorrow. Please check again after the release. 

I'm leaving this issue open so that you can try out after tomorrow and give your feedback.

**Comment by DRMacIver** [comment]
> In the original GUI which we had made, there we were a few bugs which were not fixed. A value of zero indicates Lead-off (contact) conditions.

Just to make sure I understand, that means that when a value of zero is showing one of the pads attached to me is not getting a good contact? Or could that just be a sign of bad placement? Is there a way to tell which sensor is not making good contact?

> Please check again after the release

Thanks, will do.

For when the release is out, are there instructions somewhere for how to update the firmware on the device? I couldn't find any.

**Comment by protocentralashwin** [comment]
Lead-off means that the contact impedance is too high and a no-contact condition is assumed. Bad placement in terms of location cannot be detected, you will just get a different kind of waveform. Is it possible for you to post a screenshot of the plot you're getting? 

For more information about Lead-off, this document is great: http://www.ti.com/lit/an/sbaa196a/sbaa196a.pdf

For firmware update, you can just do it through Arduino. Now that you mention it, we'll write up a document about how to do this and put that up also.

**Comment by DRMacIver** [comment]
>  Is it possible for you to post a screenshot of the plot you're getting?

Sorry, I'd already taken off the ECG sensors when I saw this. I'll do a reading and screenshot it before I update the software tomorrow so I can get a before and after comparison.

**Comment by protocentralashwin** [comment]
@DRMacIver We've posted the new release of the firmware. Please download it at https://github.com/Protocentral/protocentral-healthypi-v3/releases. 

The guide to upgrading the firmware is also now at http://healthypi.protocentral.com/firmware-upgrades.html
