### ISSUE TITLE
Temperature Sensor Connection Order

### ISSUE THREAD

**Issue by dpoleon** [Protocentral/protocentral-healthypi-v3#20]
Hi, what is the correct wire connection order for the temperature sensor? There isn't a picture in the documentation.

Thanks.

**Comment by joicetm** [comment]
Hi,
Please find attached image for temperature connection on healthy pi.

![Healthy pi Temp connection](https://user-images.githubusercontent.com/27211252/57683615-b1449080-7651-11e9-9ae5-e4055b4d8a35.jpg)

**Comment by dpoleon** [comment]
Thank you, that is great...is there any chance that you could tell me which colours relate to which positions... I'm no electrician.

**Comment by joicetm** [comment]
Hi,
Here i given color coding for temperature sensor connection,
RED-----------------VCC
GREEN--------------SCL
WHITE--------------SDA
BLACK--------------GND

**Comment by dpoleon** [comment]
Perfect!...thank you for your quick response,   it is much appreciated!
