### ISSUE TITLE
Thermometer is fairly slow to stabilise on a temperature

### ISSUE THREAD

**Issue by DRMacIver** [Protocentral/protocentral-healthypi-v3#3]
I'm testing the thermometer on my HealthyPi with an armpit reading. It seems to be taking longer than I would expect to stabilise.

When I started recording at 11:56:58 it was reporting a temperature of 29.56C (this is not the ambient temperature, so I think I had it under my armpit for about 30 seconds before I started recording). It did not report a temperature above 36C until 12:03:58 when it reported 36.02. It eventually stabilised on around 36.25C by 12:07:53, which seems a little low but is at least plausible.

It also on removal took a fairly long time to stabilise downwards. At 12:10:24 it was reporting 36.02, and seems to have stabilized on about 21.2C and first dropped below 21.5C at 12:20:45, so again about 10 minutes to update.

This seems like a long time. I've not really done a detailed analysis of temperature over time on thermometers before, but I'd typically expect a few minutes rather than ten. Is this expected behaviour?

**Comment by protocentralashwin** [comment]
@DRMacIver That is definitely not right. 

We did some testing on our own. The temperature sensor chip itself responds quite fast. However, to make it more usable and to avoid bringing any contact of the PCB directly with the body, we had attached it to a stainless steel button. The button is the one that seems to retain the heat and hence affects sensitivity. 

Can you try by carefully removing the button from the temperature sensor PCB (the small round one)? This would for sure make it more responsive, but putting a PCB directly on the skin is not what I would recommend.
