### ISSUE TITLE
Trouble updating firmware from Linux Mint (64-bit) - 'sercom2' was not declared in this scope

### ISSUE THREAD

**Issue by BanjoFox** [Protocentral/protocentral-healthypi-v3#8]
Hey guys, 
I've finally gotten around to trying out the firmware update for my HealthyPi with the touch screen.  However, when I run a check, in Arduino IDE I get an error:

'sercom2' was not declared in this scope

The system I am running on is a Linux Mint 64-bit machine, with Oracle Java 9 installed. I initially just had the healthypi hat plugged in (screen/pi powered off).  After seeing the error a second time I attached power to everything, and still had the PC direct to healthypi.  Same issue.

I might try on Windows 10 (64-bit as well), but I was wondering if I am missing something else.

Cheers!

Banjo

**Comment by VenkateshBhat** [comment]
@BanjoFox 
Please select board as Arduino Zero(Native Port) 
![zero](https://user-images.githubusercontent.com/6176131/33805130-7ded883e-ddd9-11e7-8560-4310a5aafdea.png)
let me know if you are still not able to rectify the error.

**Comment by protocentralashwin** [comment]
@BanjoFox Did this solution work out for you?

**Comment by BanjoFox** [comment]
Unfortunately no.
For some reason my laptop is not able to detect the HealthyPi board. Also tried it on Windows, but I believe my workstation is also not detecting the USB.  I believe that my workstation is USB 3 only though, which I seem to recall is not supported.

**Comment by dpoleon** [comment]
Hi,

I am having trouble compiling the latest version of the code, I get the same error message.

Can you please help?

Regards

**Comment by BanjoFox** [comment]
Hey
I FINALLY got around to trying this again, and I was able to get it resolved.  The 'sercom2' error was resolved by selecting the Arduino Native USB port, and also selecting the CORRECT COM port

Screenshot below.

![image](https://user-images.githubusercontent.com/4459812/95634784-b1b8a500-0a58-11eb-9d41-06aa94470474.png)

**Comment by joicetm** [comment]
We are glad that you were able to fix the problem.
