### ISSUE TITLE
Firmware freezes when writing to RpiSerial

### ISSUE THREAD

**Issue by luzader** [Protocentral/protocentral-healthypi-v3#9]
The arduino firmware freezes at any call to RpiSerial.write(). As a result, after resetting only one reading is returned over USB, then nothing. If all calls to RpiSerial.write are removed, the HealthyPi3 works fine, though of course, only using USB. I saw the same effect on:
- Initial release plain text
- Initial release streaming
- v1.1 plain text
- v1.1 streaming

So this must be because of a change made by Arduino.

I would suspect that Arduino have changed the procedure for initializing the sercom4 and that the firmware is hanging on a check for transmission completed from the uart peripheral (unfortunately these operations never time out).

This might be what is causing #6

**Comment by protocentralashwin** [comment]
Hi @luzader Thank you for the very detailed explanation. This makes sense, The sercom pins are not standard and the newer versions or libraries might be overriding this pin mapping is my guess. I will check this , work out an alternative and get  back. #6 also.

**Comment by joicetm** [comment]
Hi luzader,

It seems the Board Manger Version is causing the issue(Not the arduino version, refer to the attached image )

Please try 1.6.15 which seems to give stable result.
![zero_version](https://user-images.githubusercontent.com/27211252/35208884-7f650d64-ff70-11e7-8f04-a83627e41896.png)
![zero](https://user-images.githubusercontent.com/27211252/35208885-7faa752a-ff70-11e7-85c6-5c6e46e63f9a.JPG)

**Comment by joicetm** [comment]
Hope that your issue is solved.
you can reopen it whenever required.

**Comment by kyokusei** [comment]
No, it doesn't work with 1.6.15
Furthermore, programming with USB I see only Native Port, and not Programming port as you says on your guideline for firmware update. So I've selected the Native USB Port from the board list.

**Comment by anning865** [comment]
Finally, it works with 1.6.15
The issue should be highlighted at first.
